### ISSUE TITLE
Exception thrown if page is greater than the count of the items in pagerfanta_page_url

### ISSUE THREAD

**Issue by ste93cry** [whiteoctober/WhiteOctoberPagerfantaBundle#146] opened 2016-08-04 08:05 UTC
It seems to me that there is a call to the wrong function in `pagerfanta_page_url` function of the `PagerfantaExtension` Twig extension. In particular, at line [82](https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/blob/4b73a90177dd7d2586e73d126258324fb4fa6db8/Twig/PagerfantaExtension.php#L82) the `count()` function is called, but imho it should be `getNbPages()`.

**Comment by sampart** [comment] 2016-08-04 08:46
Can you give an example of where these two methods return different results in practice?  Or an example of a specific error the current code causes?  I don't think throwing an exception if you request a page out of bounds is an error in itself.  Are you seeing a problem caused by the current code, or is it just a theoretical issue?  Thanks

**Comment by ste93cry** [comment] 2016-08-04 08:55
I think I explained bad the problem. The issue is real: if the number of items is 0, the first page should still be available (and it will just display no records). With the actual code, an exception is thrown because the `count()` method returns the number of items available and not the number of pages available (which in this case should be 1).

**Comment by sampart** [comment] 2016-08-04 12:56
Thanks for explaining @ste93cry, that makes a lot of sense.  I've pushed a fix to the problem as you'll see, and I'll merge it once someone here at White October has reviewed it.

**Comment by sampart** [comment] 2016-08-04 15:48
This fix has been merged now as you'll see.  Thanks again for the suggestion.

**Closed** 2016-08-04 15:48 UTC

**Comment by ste93cry** [comment] 2016-08-04 16:38
Do you have any plan to release a new version of the bundle with the fix integrated?

**Comment by sampart** [comment] 2016-08-05 07:50
Good idea.  Here you go: https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/releases/tag/v1.0.7
